# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Univ.create(univ: '유니스트')
Univ.create(univ: '강원대학교')
Univ.create(univ: '건국대학교')
Univ.create(univ: '경북대학교')
Univ.create(univ: '경희대학교')
Univ.create(univ: '고려대학교')
Univ.create(univ: '국민대학교')
Univ.create(univ: '단국대학교')
Univ.create(univ: '덕성여자대학교')
Univ.create(univ: '동국대학교')
Univ.create(univ: '동덕여자대학교')
Univ.create(univ: '부산대학교')
Univ.create(univ: '서강대학교')
Univ.create(univ: '서울과학기술대학교')
Univ.create(univ: '서울대학교')
Univ.create(univ: '서울시립대학교')
Univ.create(univ: '성균관대학교')
Univ.create(univ: '성신여자대학교')
Univ.create(univ: '숙명여자대학교')
Univ.create(univ: '아주대학교')
Univ.create(univ: '연세대학교')
Univ.create(univ: '영남대학교')
Univ.create(univ: '원광대학교')
Univ.create(univ: '이화여자대학교')
Univ.create(univ: '인하대학교')
Univ.create(univ: '전남대학교')
Univ.create(univ: '중앙대학교')
Univ.create(univ: '충남대학교')
Univ.create(univ: '평택대학교')
Univ.create(univ: '한국과학기술원')
Univ.create(univ: '한국예술종합학교')
Univ.create(univ: '한국외국어대학교')
Univ.create(univ: '한동대학교')
Univ.create(univ: '한양대학교')
